### ISSUE TITLE
Some mandatory parameters are missing ("pos") to generate a URL for route "de__RG__munewsmodule_message_adminview".

### ISSUE THREAD

**Issue by rallek** [zikula-modules/News#142] opened 2020-07-10 17:28 UTC
After installing news lates version under ZK3 I do get the error message:
`Some mandatory parameters are missing ("pos") to generate a URL for route "de__RG__munewsmodule_message_adminview".`

here the stack tarce:

 
```

--
Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /news/admin/messages/view"    at vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:136   at Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))      (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:117)   at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))      (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:230)   at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(RequestEvent))      (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:59)   at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(RequestEvent), 'kernel.request')      (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:151)   at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(RequestEvent), 'kernel.request')      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:133)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:79)   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:196)   at Symfony\Component\HttpKernel\Kernel->handle(object(Request))      (public/index.php:35)


```

**Comment by Guite** [comment] 2020-07-11 10:03
The extension works as expected. Instead, the issue seems to be caused by the translations somehow.
Closing here, but will further investigate with you in order to fix it.

**Closed as completed by Guite** 2020-07-11 10:03 UTC
Labels: bug
